routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\PesananController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('admin')->middleware(['auth','isAdmin'])->group(function(){
    Route::get('/beranda', [UserController::class, 'dashboard'])->name('admin.beranda');
    Route::get('/user', [UserController::class, 'index'])->name('admin.user');
    Route::resource('kategori', KategoriController::class);
    Route::resource('produk', ProdukController::class);
    Route::resource('pesanan', PesananController::class);
});

Route::get('/home', [HomeController::class, 'index'])->name('home.user');

Route::get('/welcome', [HomeController::class, 'welcome'])->name('home.welcome');


//User Route
// Route::middleware(['auth','user-role:user'])->group(function()
// {
//     Route::get('/user/home',[HomeController::class, 'userHome'])->name('home.user');
// });

//Admin Route
// Route::middleware(['auth','user-role:admin'])->group(function()
// {
//     Route::get('/admin/home', [HomeController::class, 'adminHome'])->name('home.admin');
// });

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;
    protected $table = 'produks';
    protected $primaryKey = 'idProduk';
    protected $keyType = 'string';
    protected $fillable = [
        'idProduk',
        'namaProduk',
        'deskripsi',
        'hargaProduk',
        'user_id',
        'idKategori',
    ];
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Produk;
use App\Models\Kategori;
use App\Models\User;

class ProdukController extends Controller
{
    public function index(){
        $produk = Produk::all();
        return view('admin.produk.index')->with('produks', $produk);
    }

    public function create()
    {
        $user = User::where('role', '=', "1")->get();
        $kategori = Kategori::all();
        return view('admin.produk.create', compact('user', 'kategori'));
    }

    public function store(Request $request)
    {
        //melakukan validasi data
        $request->validate([
            'idProduk' => 'required',
            'namaProduk' => 'required',
            'deskripsi' => 'required',
            'hargaProduk' => 'required',
            'user_id' => 'required',
            'idKategori' => 'required',
            ]);
            //fungsi eloquent untuk menambah data
            Produk::create($request->all());
            //jika data berhasil ditambahkan, akan kembali ke halaman utama
            return redirect()->route('produk.index')->with('success', 'Produk Catering Berhasil Ditambahkan');
    }

    public function destroy($idProduk)
    {
        Produk::find($idProduk)->delete();
        return redirect()->route('produk.index')
            -> with('success', 'Produk Catering Berhasil Dihapus');
    }

    public function show($idProduk)
    {
        $produk = Produk::find($idProduk);
        return view('admin.produk.detail', compact('produk'));
    }

    public function edit($idProduk)
    {
        $produk = Produk::find($idProduk);
        return view('admin.produk.edit', compact('produk'));
    }

}

resources/views/admin/produk/create.blade.php
@extends('layouts.index')
@section('content')
<div class="container mt-5">
   <div class="row justify-content-center align-items-center">
   <div class="card" style="width: 24rem;">
   <div class="card-header">Tambah Produk Catering</div>
   
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">      
         <strong>Whoops!</strong> There were some problems with your input.<br><br>
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      @endif
      
      <form method="post" action="{{ route('produk.store') }}" id="myForm">
         @csrf
         <div class="form-group">
            <label for="idProduk">ID Produk</label> 
            <input type="text" name="idProduk" class="form-control" id="idProduk" aria-describedby="idProduk" > 
         </div>
         <div class="form-group">
            <label for="namaProduk">Nama Produk</label> 
            <input type="text" name="namaProduk" class="form-control" id="namaProduk" aria-describedby="namaProduk" > 
         </div>
         <div class="form-group">
            <label for="deskripsi">Deskripsi</label> 
            <input type="text" name="deskripsi" class="form-control" id="deskripsi" aria-describedby="deskripsi" > 
         </div>
         <div class="form-group">
            <label for="hargaProduk">Harga Produk</label> 
            <input type="text" name="hargaProduk" class="form-control" id="hargaProduk" aria-describedby="hargaProdukhargaProduk" > 
         </div>
         <div class="form-group">
            <label for="user_id">ID User</label> 
            <select name="user_id" class="form-control">
                @foreach($user as $u)
                    <option value="{{ $u -> id }}">{{ $u -> username }}</option>
                @endforeach
            </select> 
         </div>
         <div class="form-group">
            <label for="idKategori">ID Kategori</label> 
            <select name="idKategori" class="form-control">
                @foreach($kategori as $k)
                    <option value="{{ $k -> idKategori }}">{{ $k -> namaKategori }}</option>
                @endforeach
            </select> 
         </div>
         <button type="submit" class="btn btn-primary">Submit</button>
      </form>
   </div>
</div>
</div>
</div>
@endsection

resources/views/admin/produk/detail.blade.php
@extends('layouts.index')
 @section('content')
 <div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
        <div class="card-header">Detail Produk Catering</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>ID Produk: </b>{{$produk->idProduk}}</li>
                <li class="list-group-item"><b>Nama Produk: </b>{{$produk->namaProduk}}</li>
                <li class="list-group-item"><b>Deskripsi: </b>{{$produk->deskripsi}}</li>
                <li class="list-group-item"><b>Harga Produk: </b>{{$produk->hargaProduk}}</li>
                <li class="list-group-item"><b>ID User: </b>{{$produk->user_id}}</li>
                <li class="list-group-item"><b>ID Kategori: </b>{{$produk->idKategori}}</li>
            </ul>
        </div>
        <a class="btn btn-success mt-3" href="{{ route('produk.index') }}">Kembali</a>
    </div>
</div>
</div>
@endsection

resources/views/admin/produk/edit.blade.php
@extends('layouts.index')
 @section('content')
 <div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
        <div class="card-header">Edit Data Produk</div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form method="post" action="{{ route('produk.update', $produk->idProduk) }}" id="myForm">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="idProduk">ID Produk</label> 
                    <input type="text" name="idProduk" class="form-control" id="idProduk" value="{{ old('idProduk', $produk->idProduk) }}" aria-describedby="idProduk" > 
                </div>
                <div class="form-group">
                    <label for="namaProduk">Nama Produk</label> 
                    <input type="text" name="namaProduk" class="form-control" id="namaProduk" value="{{ old('namaProduk', $produk->namaProduk) }}" aria-describedby="namaProduk" > 
                </div>
                <div class="form-group">
                    <label for="deskripsi">Deskripsi</label> 
                    <input type="text" name="deskripsi" class="form-control" id="deskripsi" value="{{ old('deskripsi', $produk->deskripsi) }}" aria-describedby="deskripsi" > 
                </div>
                <div class="form-group">
                    <label for="hargaProduk">Harga Produk</label> 
                    <input type="text" name="hargaProduk" class="form-control" id="hargaProduk" value="{{ old('hargaProduk', $produk->hargaProduk) }}" aria-describedby="hargaProduk" > 
                </div>
                <div class="form-group">
                    <label for="user_id">id User</label> 
                    <select name="user_id" class="form-control" id="user">
                        @foreach($user as $u)
                            <option value="{{ old('user_id', $u -> user_id) }}">{{ $u -> name }}</option>
                        @endforeach
                    </select>
                </div>
                <!-- <div class="form-group">
                    <label for="idUser">ID User</label>
                    <select name="idUser" class="form-control" id="user">
                        @foreach($user as $u)
                            <option value="{{ $u -> idUser }}">{{ $u -> username }}</option>
                        @endforeach
                    </select>

                    <script>
                        document.getElementById('user').addEventListener('change', function() {
                            var selectedOption = this.value;
                            localStorage.setItem('selectedOption', selectedOption);
                        });
                    </script>
                </div> -->
                <div class="form-group">
                    <label for="idKategori">ID Kategori</label> 
                    <select name="idKategori" class="form-control">
                        @foreach($kategori as $k)
                            <option value="{{ $k -> idKategori }}">{{ $k -> namaKategori }}</option>
                        @endforeach
                    </select> 
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/admin/produk/index.blade.php
@extends('layouts.index')
@section('content')
<div class="col-md-12 d-flex flex-row justify-content-end">
    <a class="btn btn-success" href="{{ route('produk.create') }}"> Input Produk Catering</a>
</div>
<section class="content-header">
    <div class="container-fluid">
    </div><!-- /.container-fluid -->
</section>
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Produk Catering</h3><br>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>  
            <div class="card-body">
                <table class="table">
                <thead>
                    <tr>
                        <th>ID Produk</th>
                        <th>Nama Produk</th>
                        <th>Deskripsi</th>
                        <th>Harga</th>
                        <th>ID User</th>
                        <th>ID Kategori</th>
                        <th width="280px">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($produks as $p)
                        <tr>
                            <td>{{ $p -> idProduk}}</td>
                            <td>{{ $p -> namaProduk}}</td>
                            <td>{{ $p -> deskripsi}}</td>
                            <td><span>Rp. </span>{{ $p -> hargaProduk}}</td>
                            <td>{{ $p -> user_id}}</td>
                            <td>{{ $p -> idKategori}}</td>
                            <td>
                                <form action="{{ route('produk.destroy',$p->idProduk) }}" method="POST">
                                    <a class="btn btn-info" href="{{ route('produk.show',$p->idProduk) }}">Show</a>
                                    <a class="btn btn-primary" href="{{ route('produk.edit',$p->idProduk) }}">Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                </table>
                <div class="col-md-12">
                    {{ $produks->links() }}
                </div>
            </div>
        </div>
    </section>
@endsection