routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\PesananController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('admin')->middleware(['auth','isAdmin'])->group(function(){
    Route::get('/beranda', [UserController::class, 'dashboard'])->name('admin.beranda');
    Route::get('/user', [UserController::class, 'index'])->name('admin.user');
    Route::resource('kategori', KategoriController::class);
    Route::resource('produk', ProdukController::class);
    Route::resource('pesanan', PesananController::class);
});

Route::get('/home', [HomeController::class, 'index'])->name('home.user');

Route::get('/welcome', [HomeController::class, 'welcome'])->name('home.welcome');


//User Route
// Route::middleware(['auth','user-role:user'])->group(function()
// {
//     Route::get('/user/home',[HomeController::class, 'userHome'])->name('home.user');
// });

//Admin Route
// Route::middleware(['auth','user-role:admin'])->group(function()
// {
//     Route::get('/admin/home', [HomeController::class, 'adminHome'])->name('home.admin');
// });

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;
    protected $table = 'kategoris';
    protected $primaryKey = 'idKategori';
    protected $keyType = 'string';
    protected $fillable = [
        'idKategori',
        'namaKategori',
    ];
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kategori;

class KategoriController extends Controller
{
    public function index(){
        $kategori = Kategori::all();
        return view('admin.kategori.index')->with('kategoris', $kategori);
    }

    public function create()
    {
        return view('admin.kategori.create');
    }

    public function store(Request $request)
    {
        //melakukan validasi data
        $request->validate([
            'idKategori' => 'required',
            'namaKategori' => 'required',
            ]);
            //fungsi eloquent untuk menambah data
            Kategori::create($request->all());
            //jika data berhasil ditambahkan, akan kembali ke halaman utama
            return redirect()->route('kategori.index')->with('success', 'Kategori Catering Berhasil Ditambahkan');
    }

    public function destroy($idKategori)
    {
        Kategori::find($idKategori)->delete();
        return redirect()->route('kategori.index')
            -> with('success', 'Kategori Catering Berhasil Dihapus');
    }

    public function show($idKategori)
    {
        $kategori = Kategori::find($idKategori);
        return view('admin.kategori.detail', compact('kategori'));
    }

    public function edit($idKategori)
    {
        $kategori = Kategori::find($idKategori);
        return view('admin.kategori.edit', compact('kategori'));
    }

    public function update(Request $request, string $idKategori)
    {
        //melakukan validasi data
        $request->validate([
            'idKategori' => 'required',
            'namaKategori' => 'required',
            ]);
        //fungsi eloquent untuk mengupdate data inputan kita
            Kategori::find($idKategori)->update($request->all());
        //jika data berhasil diupdate, akan kembali ke halaman utama
            return redirect()->route('kategori.index')->with('success', 'Kategori Catering Berhasil Diupdate');
    }
}

resources/views/admin/kategori/create.blade.php
@extends('layouts.index')
@section('content')
<div class="container mt-5">
   <div class="row justify-content-center align-items-center">
   <div class="card" style="width: 24rem;">
   <div class="card-header">Tambah Kategori Catering</div>
   
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">      
         <strong>Whoops!</strong> There were some problems with your input.<br><br>
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      @endif
      
      <form method="post" action="{{ route('kategori.store') }}" id="myForm">
         @csrf
         <div class="form-group">
            <label for="idKategori">ID Kategori</label> 
            <input type="text" name="idKategori" class="form-control" id="idKategori" aria-describedby="idKategori" > 
         </div>
         <div class="form-group">
            <label for="namaKategori">Nama Kategori</label> 
            <input type="text" name="namaKategori" class="form-control" id="namaKategori" aria-describedby="namaKategori" > 
         </div>
         <button type="submit" class="btn btn-primary">Submit</button>
      </form>
   </div>
</div>
</div>
</div>
@endsection

resources/views/admin/kategori/detail.blade.php
@extends('layouts.index')
 @section('content')
 <div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
        <div class="card-header">Detail Kategori Catering</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>ID Kategori: </b>{{$kategori->idKategori}}</li>
                <li class="list-group-item"><b>Nama Kategori: </b>{{$kategori->namaKategori}}</li>
            </ul>
        </div>
        <a class="btn btn-success mt-3" href="{{ route('kategori.index') }}">Kembali</a>
    </div>
</div>
</div>
@endsection

resources/views/admin/kategori/edit.blade.php
@extends('layouts.index')
 @section('content')
 <div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
        <div class="card-header">Edit Kategori Catering</div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form method="post" action="{{ route('kategori.update', $kategori->idKategori) }}" id="myForm">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="idKategori">ID Kategori</label> 
                    <input type="text" name="idKategori" class="form-control" id="idKategori" value="{{ $kategori->idKategori }}" aria-describedby="idKategori" > 
                </div>
                <div class="form-group">
                    <label for="namaKategori">Nama Kategori</label> 
                    <input type="text" name="namaKategori" class="form-control" id="namaKategori" value="{{ $kategori->namaKategori }}" aria-describedby="namaKategori" > 
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/admin/kategori/index.blade.php
@extends('layouts.index')
@section('content')
<div class="col-md-12 d-flex flex-row justify-content-end">
    <a class="btn btn-success" href="{{ route('kategori.create') }}"> Input Kategori Catering</a>
</div>
<section class="content-header">
    <div class="container-fluid">
    </div><!-- /.container-fluid -->
</section>
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Kategori Catering</h3><br>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>  
            <div class="card-body">
                <table class="table">
                <thead>
                    <tr>
                        <th>ID Kategori</th>
                        <th>Nama Kategori</th>
                        <th width="280px">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($kategoris as $k)
                        <tr>
                            <td>{{ $k -> idKategori}}</td>
                            <td>{{ $k -> namaKategori}}</td>
                            <td>
                                <form action="{{ route('kategori.destroy',$k->idKategori) }}" method="POST">
                                    <a class="btn btn-info" href="{{ route('kategori.show',$k->idKategori) }}">Show</a>
                                    <a class="btn btn-primary" href="{{ route('kategori.edit',$k->idKategori) }}">Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <!-- <div class="card-footer">
                --
            </div> -->
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->

    </section>
@endsection